---
- name: Install common packages
  hosts: nodes
  gather_facts: true
  roles:
    - { role: common, tags: ["common"] }

- name: Install docker
  hosts: nodes
  gather_facts: true
  roles:
    - { role: docker, tags: ["docker"] }

- name: Install celestia node
  hosts: nodes
  gather_facts: true
  roles:
    - { role: node, tags: ["node"] }
