---
- name: Install python dependencies
  become: true
  apt:
    name: python3-pip
    state: latest
    update_cache: yes

- name: Check if pip requests, pip docker, pip docker-compose are installed
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - requests==2.29.0
    - docker
    - docker-compose
